// Selection of Jack Handy's deep thoughts
module.exports = [
    'If you get invited to your first orgy, don\'t just show up nude. That\'s a common mistake. You have to let nudity "happen."',
    'It\'s funny that pirates were always going around searching for treasure, and they never realized that the real treasure was the fond memories they were creating.',
    'If the Vikings were around today, they would probably be amazed at how much glow-in-the-dark stuff we have, and how we take so much of it for granted.',
    'If you were a gladiator in olden days, I bet the inefficiency of how the gladiator fights were organized and scheduled would just drive you up a wall.',
    'It\'s easy to sit there and say you\'d like to have more money. And I guess that\'s what I like about it. It\'s easy. Just sitting there, rocking back and forth, wanting that money.',
    'I hope that after I die, people will say of me: "That guy sure owed me a lot of money.',
    'It takes a big man to cry, but it takes a bigger man to laugh at that man.',
    'Dad always thought laughter was the best medicine, which I guess is why several of us died of tuberculosis.',
    'Anytime I see something screech across a room and latch onto someone\'s neck, and the guy screams and tries to get it off, I have to laugh, because what IS that thing?!',
    'If you ever drop your keys into a river of molten lava, let \'em go, because, man, they\'re gone.',
    'One thing a computer can do that most humans can\'t is be sealed up in a cardboard box and sit in a warehouse.',
    'I wish I had a dollar for every time I spent a dollar, because then, yahoo!, I\'d have all my money back.',
    'Like jewels in a crown, the precious stones glittered in the queen\'s round metal hat.',
    'If I ever get real rich, I hope I\'m not real mean to poor people, like I am now.',
    'I bet it was pretty hard to pick up girls if you had the Black Death.',
    'I hope they never find out that lightning has a lot of vitamins in it, because do you hide from it or not?',
    'For mad scientists who keep brains in jars, here\'s a tip: Why not add a slice of lemon to each jar, for freshness.',
    'To me, it\'s always a good idea to always carry two sacks of something when you walk around. That way, if anybody says, "Hey, can you give me a hand?," you can say, "Sorry, got these sacks."',
    "If a kid asks where rain comes from, I think a cute thing to tell him is, 'God is crying.' And if he asks why God is crying, another cute thing to tell him is, 'Probably because of something you did.'",
    "To me, clowns aren't funny. In fact, they're kinda scary. I've wondered where this started and I think it goes back to the time I went to the circus and a clown killed my dad.",
    "I can picture in my mind a world without war, a world without hate. And I can picture us attacking that world, because they'd never expect it.",
    "Most of the time it was probably real bad being stuck down in a dungeon. But some days, when there was a bad storm outside, you'd look out your little window and think, 'Boy, I'm glad I'm not out in that.'",
    "One thing vampire children have to be taught early on is, don't run with a wooden stake.",
    "Consider the daffodil. And while you're doing that, I'll be over here, looking through your stuff.",
    "Somebody told me how frightening it was how much topsoil we are losing each year, but I told that story around the campfire and nobody got scared.",
    "When I found the skull in the woods, the first thing I did was call the police. But then I got curious about it. I picked it up, and started wondering who this person was, and why he had deer horns."
];